version: "3.8"
services:
  nginx:
    image: nginx:1.20
    ports:
      - 8000:8000
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./:/var/www/html
    links:
      - php
  php:
    build: ./
    volumes:
      - ./:/var/www/html
