#!/bin/bash
#
# Initializes everything for the repository.

cd "$(dirname "$0")/.."

echo -e "\n\033[1;34mInstalling npm dependencies\033[0m"
npm i

echo -e "\n\033[1;34mInstalling composer dependencies\033[0m"
composer install

echo -e "\n\033[1;34mSetting up git hook for code formatting\033[0m"
./scripts/add-git-hooks

echo -e "\n\033[1;34mCreating dummy content repos\033[0m"
./scripts/create-repos

echo -e "\n\033[1;32mInitialization successful!\033[0m"
