#!/bin/bash

git diff-index --cached --name-only HEAD | while read -r file; do
	case "$file" in
		*.php)
			output=$(vendor/bin/php-cs-fixer fix "$file" --dry-run --diff 2>&1)
		;;

		*.js | *.vue)
			output=$(node_modules/.bin/prettier "$file" --check 2>&1)
		;;
	esac

	status=$?

	if [ $status != 0 ]; then
		echo -e "Incorrectly formatted: $file (exit code $status)."
		echo "Formatter output:"
		echo "$output"
		exit 1
	fi
done